In [1]:
import numdifftools as nd
import numpy as np

In [2]:
def six_hump_camel(x):
    return (x[0]**6/3) - 2.1*x[0]**4 + 4*x[1]**4 + 4*x[0]**2 -  4*x[1]**2 + x[0]*x[1]

In [3]:
grad0 = nd.Gradient(six_hump_camel)([-1,1])

In [4]:
grad0

array([-0.6,  7. ])

In [5]:
grad0_2d = grad0[..., np.newaxis]

In [6]:
d0 = -grad0_2d

In [7]:
from sympy import *
alfa = symbols('alfa')
x0 = (-1-alfa*(-0.6)) 
x1 =(1 - alfa*7)
y = [x0,x1]
f = six_hump_camel(y)

ff = diff(f, alfa)
ff
#{{alfa -> 0.034644}, {alfa -> 0.155721}, {alfa -> 0.238163}}

-397.52*alfa - 112*(1 - 7*alfa)**3 + 1.2*(0.6*alfa - 1)**5 - 5.04*(0.6*alfa - 1)**3 + 58.8

In [8]:
alfa0 = 0.034644
x0_0 = (-1-alfa0*(-0.6)) 
x1_0 =(1 - alfa0*7)

In [9]:
alfa0 = 0.034644
x0_0 = (-1-alfa0*(-0.6)) 
x1_0 =(1 - alfa0*7)

In [10]:
print(x0_0)
print(x1_0)

-0.9792136
0.757492


In [11]:
grad1 = nd.Gradient(six_hump_camel)([x0_0,x1_0])

In [12]:
grad1_2d = grad1[..., np.newaxis]

In [13]:
grad1_2d

array([[-0.98982097],
       [-0.08483819]])

In [14]:
d0 

array([[ 0.6],
       [-7. ]])

In [15]:
# Fletcher-Reeves formula: 
beta1 = ()

In [16]:
import numpy as np
x = np.array([[1],[2]])
norm_grad0 = (np.linalg.norm(grad0_2d,ord=2))**2
norm_grad1 = (np.linalg.norm(grad1_2d,ord=2))**2

In [17]:
beta1 = norm_grad1/norm_grad0

In [18]:
d1 = -grad1_2d + beta1*d0

In [19]:
d1

array([[ 1.00181785],
       [-0.05512537]])

In [22]:
from sympy import *
alfa = symbols('alfa')
x0 = (-0.9792136+ alfa *(1.00181785)) 
x1 =(0.757492 + alfa *(-0.05512537))
y = [x0,x1]
f = six_hump_camel(y)

ff = diff(f, alfa)
ff

7.89435042598017*alfa - 0.38335898961155*(1 - 0.0727735342419458*alfa)**3 + 2.02191357797565*(alfa - 0.977436766573884)**5 - 8.46124651269717*(alfa - 0.977436766573884)**3 - 6.70104457452453

In [23]:
# {{alfa -> -0.723063}, {alfa -> -0.129705}, {alfa -> 0.887814}, {alfa -> 2.27304}, {alfa -> 2.57909}}

In [24]:
alfa1 = 0.887814
x0_1 = (-0.9792136+alfa1*(1.00181785)) 
x1_1 =(0.757492+alfa1*(-0.05512537))

In [25]:
print(x0_1)
print(x1_1)

-0.08978568732010006
0.7085509247588201


In [26]:
six_hump_camel([-0.9792136,0.757492])

0.47857155283954844

In [27]:
six_hump_camel([-0.08978568732010006,0.7085509247588201])

-1.0314914333769314

In [28]:
grad2 = nd.Gradient(six_hump_camel)([x0_1,x1_1])
grad2_2d = grad2[..., np.newaxis]
grad2_2d

array([[-0.00366629],
       [-0.06660856]])

In [29]:
d1

array([[ 1.00181785],
       [-0.05512537]])

In [30]:
import numpy as np

norm_grad1 = (np.linalg.norm(grad1_2d,ord=2))**2
norm_grad2 = (np.linalg.norm(grad2_2d,ord=2))**2

In [31]:
beta2 = norm_grad2/norm_grad1

In [32]:
d2 = -grad2_2d + beta2*d1

In [33]:
d2

array([[0.0081835 ],
       [0.06635999]])

In [35]:
from sympy import *
alfa = symbols('alfa')
x0 = (-0.08978568732010006+ alfa *(0.0081835)) 
x1 =(0.7085509247588201 + alfa *(0.06635999))
y = [x0,x1]
f = six_hump_camel(y)

ff = diff(f, alfa)
ff
# {{alfa -> 0.0608733}}

-0.0336073148480708*alfa + 9.55002789845859e-8*(0.0911448165543862*alfa - 1)**5 - 4.97553410571385e-5*(0.0911448165543862*alfa - 1)**3 + 0.377693492452011*(0.0936559217992524*alfa + 1)**3 - 0.382193298449302

In [36]:
alfa2 = 0.0608733
x0_2 = (-0.08978568732010006+alfa2*(0.0081835 )) 
x1_2 =(0.7085509247588201+alfa2*(0.06635999))

In [37]:
print(x0_2)
print(x1_2)

-0.08928753066955006
0.7125904763380871


In [38]:
six_hump_camel([-0.08928753066955006,0.7125904763380871])

-1.0316272556933292